# Generated by Django 4.2.2 on 2023-09-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0006_alter_userprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
