# Generated by Django 4.2.2 on 2023-09-18 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0009_followerfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='followerfollowing',
            name='follower_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followerfollowing',
            name='leader_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='followerfollowing',
            unique_together={('leader_id', 'follower_id')},
        ),
    ]
