# Generated by Django 4.2.2 on 2023-09-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0010_followerfollowing_follower_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerFollowing',
        ),
    ]
