# Generated by Django 4.2.2 on 2023-09-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0012_followerfollowing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followerfollowing',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='followerfollowing',
            old_name='leader_id',
            new_name='leader',
        ),
    ]
