# Generated by Django 4.2.2 on 2023-09-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0013_rename_follower_id_followerfollowing_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follower_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
