# Generated by Django 4.2.2 on 2023-10-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picpost',
            name='likes_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
