# Generated by Django 4.2.2 on 2023-10-03 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pic_board', '0004_rename_user_likepost_liked_by_likepost_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('post', 'liked_by')},
        ),
    ]
