# Generated by Django 4.2.2 on 2023-10-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_board', '0006_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='picpost',
            name='comments_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
