# Generated by Django 4.2.2 on 2023-10-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic_board', '0007_picpost_comments_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='user',
            new_name='commenter',
        ),
    ]
