# Generated by Django 4.2.2 on 2023-10-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic_board', '0008_rename_user_commentpost_commenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='parent',
            new_name='reply_to_comment',
        ),
    ]
