# Generated by Django 4.2.2 on 2023-10-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pic_board', '0010_commentpost_level_commentpost_lft_commentpost_rght_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentpost',
            old_name='reply_to_comment',
            new_name='parent',
        ),
    ]
